version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: surface_inspection
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    container_name: backend
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=surface_inspection
      - SESSION_SECRET=your_secret_key
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    entrypoint: ["sh", "-c", "until mysqladmin ping -h mysql --silent; do echo 'waiting for mysql'; sleep 2; done && npm start"]

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  mysql_data:
